substitutions:
  _NODE_VERSION_15: 15.13.0
  _NODE_VERSION_14: 14.16.1
  _NODE_VERSION_12: 12.22.1
  _NODE_VERSION_10: 10.24.1
  _YARN_VERSION: 1.22.10
  _NPM_VERSION: 7.8.0
steps:
  # copy build key to workspace
  - name: 'gcr.io/cloud-builders/gsutil'
    args: [
            'cp',
            'gs://connectedcars-staging-cloudbuilder-private/build.key',
            '.'
          ]
  #
  # node 15.x
  #
  # Build base image
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker build --target base --build-arg=NODE_VERSION=${_NODE_VERSION_15} --build-arg=NPM_VERSION=${_NPM_VERSION} --build-arg=YARN_VERSION=${_YARN_VERSION} --tag=gcr.io/${PROJECT_ID}/node-base.${BRANCH_NAME}:${_NODE_VERSION_15} --tag=gcr.io/${PROJECT_ID}/node-base.${BRANCH_NAME}:15.x .']
   # Build builder image
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker build --target builder --build-arg=NODE_VERSION=${_NODE_VERSION_15} --build-arg=NPM_VERSION=${_NPM_VERSION} --build-arg=YARN_VERSION=${_YARN_VERSION} --tag=gcr.io/${PROJECT_ID}/node-builder.${BRANCH_NAME}:${_NODE_VERSION_15} --tag=gcr.io/${PROJECT_ID}/node-builder.${BRANCH_NAME}:15.x .']
  # Run test build
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker build --build-arg=NODE_VERSION=${_NODE_VERSION_15} --build-arg=BRANCH_NAME=${BRANCH_NAME} --tag=test:${_NODE_VERSION_15} --build-arg=SSH_KEY_PASSWORD=$$GITHUB_PAT --build-arg=NPM_TOKEN=$$NPM_TOKEN test/']
    secretEnv: ['GITHUB_PAT', "NPM_TOKEN"]
  # Run test build
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker run test:${_NODE_VERSION_15}']
  # Build fatbase
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker build --build-arg=NODE_VERSION=${_NODE_VERSION_15} --build-arg=BRANCH_NAME=${BRANCH_NAME} --tag=gcr.io/${PROJECT_ID}/node-fat-base.${BRANCH_NAME}:${_NODE_VERSION_15} --tag=gcr.io/${PROJECT_ID}/node-fat-base.${BRANCH_NAME}:15.x fat-base/']
  # Run test build - package json replace
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker build --build-arg=NODE_VERSION=${_NODE_VERSION_15} --build-arg=BRANCH_NAME=${BRANCH_NAME} --tag=test:${_NODE_VERSION_15}-github-pat --build-arg=GITHUB_PAT=$$GITHUB_PAT --build-arg=NPM_TOKEN=$$NPM_TOKEN test/']
    secretEnv: ['GITHUB_PAT', "NPM_TOKEN"]
  # node 14.x
  #
  # Build base image
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker build --target base --build-arg=NODE_VERSION=${_NODE_VERSION_14} --build-arg=NPM_VERSION=${_NPM_VERSION} --build-arg=YARN_VERSION=${_YARN_VERSION} --tag=gcr.io/${PROJECT_ID}/node-base.${BRANCH_NAME}:${_NODE_VERSION_14} --tag=gcr.io/${PROJECT_ID}/node-base.${BRANCH_NAME}:14.x .']
  # Build builder image
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker build --target builder --build-arg=NODE_VERSION=${_NODE_VERSION_14} --build-arg=NPM_VERSION=${_NPM_VERSION} --build-arg=YARN_VERSION=${_YARN_VERSION} --tag=gcr.io/${PROJECT_ID}/node-builder.${BRANCH_NAME}:${_NODE_VERSION_14} --tag=gcr.io/${PROJECT_ID}/node-builder.${BRANCH_NAME}:14.x .']
  # Build test image as builder
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker build --build-arg=NODE_VERSION=${_NODE_VERSION_14} --build-arg=BRANCH_NAME=${BRANCH_NAME} --tag=test:${_NODE_VERSION_14} --build-arg=SSH_KEY_PASSWORD=$$GITHUB_PAT --build-arg=NPM_TOKEN=$$NPM_TOKEN test/']
    secretEnv: ['GITHUB_PAT', "NPM_TOKEN"]
  # Run test build
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker run test:${_NODE_VERSION_14}']
  # Build fatbase
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker build --build-arg=NODE_VERSION=${_NODE_VERSION_14} --build-arg=BRANCH_NAME=${BRANCH_NAME} --tag=gcr.io/${PROJECT_ID}/node-fat-base.${BRANCH_NAME}:${_NODE_VERSION_14} --tag=gcr.io/${PROJECT_ID}/node-fat-base.${BRANCH_NAME}:14.x fat-base/']
    secretEnv: ['GITHUB_PAT', "NPM_TOKEN"]
  #
  # node 12.x
  #
  # Build base image
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker build --target base --build-arg=NODE_VERSION=${_NODE_VERSION_12} --build-arg=NPM_VERSION=${_NPM_VERSION} --build-arg=YARN_VERSION=${_YARN_VERSION} --tag=gcr.io/${PROJECT_ID}/node-base.${BRANCH_NAME}:${_NODE_VERSION_12} --tag=gcr.io/${PROJECT_ID}/node-base.${BRANCH_NAME}:12.x .']
  # Build builder image
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker build --target builder --build-arg=NODE_VERSION=${_NODE_VERSION_12} --build-arg=NPM_VERSION=${_NPM_VERSION} --build-arg=YARN_VERSION=${_YARN_VERSION} --tag=gcr.io/${PROJECT_ID}/node-builder.${BRANCH_NAME}:${_NODE_VERSION_12} --tag=gcr.io/${PROJECT_ID}/node-builder.${BRANCH_NAME}:12.x .']
  # Build test image as builder
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker build --build-arg=NODE_VERSION=${_NODE_VERSION_12} --build-arg=BRANCH_NAME=${BRANCH_NAME} --tag=test:${_NODE_VERSION_12} --build-arg=SSH_KEY_PASSWORD=$$GITHUB_PAT --build-arg=NPM_TOKEN=$$NPM_TOKEN test/']
    secretEnv: ['GITHUB_PAT', "NPM_TOKEN"]
  # Run test build
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker run test:${_NODE_VERSION_12}']
  # Build fatbase
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker build --build-arg=NODE_VERSION=${_NODE_VERSION_12} --build-arg=BRANCH_NAME=${BRANCH_NAME} --tag=gcr.io/${PROJECT_ID}/node-fat-base.${BRANCH_NAME}:${_NODE_VERSION_12} --tag=gcr.io/${PROJECT_ID}/node-fat-base.${BRANCH_NAME}:12.x --build-arg=GITHUB_PAT=$$GITHUB_PAT fat-base/']
  #
  # node 10.x
  #
  # Build base image
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker build --target base --build-arg=NODE_VERSION=${_NODE_VERSION_10} --build-arg=NPM_VERSION=${_NPM_VERSION} --build-arg=YARN_VERSION=${_YARN_VERSION} --tag=gcr.io/${PROJECT_ID}/node-base.${BRANCH_NAME}:${_NODE_VERSION_10} --tag=gcr.io/${PROJECT_ID}/node-base.${BRANCH_NAME}:10.x .']
   # Build builder image
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker build --target builder --build-arg=NODE_VERSION=${_NODE_VERSION_10} --build-arg=NPM_VERSION=${_NPM_VERSION} --build-arg=YARN_VERSION=${_YARN_VERSION} --tag=gcr.io/${PROJECT_ID}/node-builder.${BRANCH_NAME}:${_NODE_VERSION_10} --tag=gcr.io/${PROJECT_ID}/node-builder.${BRANCH_NAME}:10.x .']
  # Run test build
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker build --build-arg=NODE_VERSION=${_NODE_VERSION_10} --build-arg=BRANCH_NAME=${BRANCH_NAME} --tag=test:${_NODE_VERSION_10} --build-arg=SSH_KEY_PASSWORD=$$GITHUB_PAT --build-arg=NPM_TOKEN=$$NPM_TOKEN test/']
    secretEnv: ['GITHUB_PAT', "NPM_TOKEN"]
  # Run test build
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker run test:${_NODE_VERSION_10}']
  # Build fatbase
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker build --build-arg=NODE_VERSION=${_NODE_VERSION_10} --build-arg=BRANCH_NAME=${BRANCH_NAME} --tag=gcr.io/${PROJECT_ID}/node-fat-base.${BRANCH_NAME}:${_NODE_VERSION_10} --tag=gcr.io/${PROJECT_ID}/node-fat-base.${BRANCH_NAME}:10.x fat-base/']
  # Run test build - package json replace
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker build --build-arg=NODE_VERSION=${_NODE_VERSION_10} --build-arg=BRANCH_NAME=${BRANCH_NAME} --tag=test:${_NODE_VERSION_10}-github-pat --build-arg=GITHUB_PAT=$$GITHUB_PAT --build-arg=NPM_TOKEN=$$NPM_TOKEN test/']
    secretEnv: ['GITHUB_PAT', "NPM_TOKEN"]
images: 
  - 'gcr.io/${PROJECT_ID}/node-base.${BRANCH_NAME}:14.x'
  - 'gcr.io/${PROJECT_ID}/node-base.${BRANCH_NAME}:${_NODE_VERSION_14}'
  - 'gcr.io/${PROJECT_ID}/node-fat-base.${BRANCH_NAME}:14.x'
  - 'gcr.io/${PROJECT_ID}/node-fat-base.${BRANCH_NAME}:${_NODE_VERSION_14}'
  - 'gcr.io/${PROJECT_ID}/node-builder.${BRANCH_NAME}:14.x'
  - 'gcr.io/${PROJECT_ID}/node-builder.${BRANCH_NAME}:${_NODE_VERSION_14}'
  - 'gcr.io/${PROJECT_ID}/node-base.${BRANCH_NAME}:12.x'
  - 'gcr.io/${PROJECT_ID}/node-base.${BRANCH_NAME}:${_NODE_VERSION_12}'
  - 'gcr.io/${PROJECT_ID}/node-fat-base.${BRANCH_NAME}:12.x'
  - 'gcr.io/${PROJECT_ID}/node-fat-base.${BRANCH_NAME}:${_NODE_VERSION_12}'
  - 'gcr.io/${PROJECT_ID}/node-builder.${BRANCH_NAME}:12.x'
  - 'gcr.io/${PROJECT_ID}/node-builder.${BRANCH_NAME}:${_NODE_VERSION_12}'
  - 'gcr.io/${PROJECT_ID}/node-base.${BRANCH_NAME}:10.x'
  - 'gcr.io/${PROJECT_ID}/node-base.${BRANCH_NAME}:${_NODE_VERSION_10}'
  - 'gcr.io/${PROJECT_ID}/node-fat-base.${BRANCH_NAME}:10.x'
  - 'gcr.io/${PROJECT_ID}/node-fat-base.${BRANCH_NAME}:${_NODE_VERSION_10}'
  - 'gcr.io/${PROJECT_ID}/node-builder.${BRANCH_NAME}:10.x'
  - 'gcr.io/${PROJECT_ID}/node-builder.${BRANCH_NAME}:${_NODE_VERSION_10}'
secrets:
- kmsKeyName: projects/connectedcars-staging/locations/global/keyRings/cloudbuilder/cryptoKeys/connectedcars-builder
  secretEnv:
    GITHUB_PAT: CiQAg7wCPfO2Tf9mtZoFWjAtX7whQ481af3gyGdM9WNK26B74UkSUQBefMgeHNh0KTsGybKReXDsFcbmed7f5sw97zSe9cswpKogENM5Ye0jiIu6NfebUpCnmJ9HVHmD/yBknlW4nn1VXBs7HYGiBSFZ52i2HyEopw==
    NPM_TOKEN: CiQAg7wCPewIVIbfIFEcQIzhDPtFwwkVhuKsZz27ikGInbEjyrcSTABefMgezLQ+uMbN3cBIleg8ogOwhKOWV/99N9Ra9HNnfwCA6n7aL443W6eiEQavWArDqlS57K0FbW0BRd+JfShkXBCojePXbCto3X8=
timeout: 2400s
