steps:
  # Setup docker with buildkit and other fixes
  - name: "europe-west1-docker.pkg.dev/connectedcars-build/cloud-build-init/master"
  # Build all images
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args: ["-c", "./build-all.sh"]
    env:
      [
        "COMMIT_SHA=${COMMIT_SHA}",
        "BRANCH_NAME=${BRANCH_NAME}",
        "PROJECT_ID=${PROJECT_ID}",
        "PUSH=y",
      ]
    secretEnv: ["NPM_TOKEN"]
    timeout: 14400s
secrets:
  - kmsKeyName: projects/connectedcars-staging/locations/global/keyRings/cloudbuilder/cryptoKeys/connectedcars-builder
    secretEnv:
      NPM_TOKEN: CiQAg7wCPVeKBJVqujmk02uI4owtZsWEJ2Sf9LrGCzUV1m71EzwSUQBefMgeHfbiWdKblpOu7pLeYKmdgmRiNLNQspz4CMEQd5oIXY8mQieqzufpTQfK8DZrJptu3CwOdbRQc825npmy9380D4p/QoGL0EZMZ0tWcQ==
timeout: 14460s
options:
  machineType: "E2_HIGHCPU_32"
