steps:
  # node 10.9.0
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker build --target base --build-arg=NODE_VERSION=10.9.0 --tag=gcr.io/$PROJECT_ID/node-base.$BRANCH_NAME:10.9.0 --tag=gcr.io/$PROJECT_ID/node-base.$BRANCH_NAME:10.x --build-arg=NPM_VERSION=6.4.0 --build-arg=YARN_VERSION=1.9.4 --build-arg=GITHUB_PAT=$$GITHUB_PAT .']
    secretEnv: ['GITHUB_PAT']
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker build --target builder --build-arg=NODE_VERSION=10.9.0 --tag=gcr.io/$PROJECT_ID/node-builder.$BRANCH_NAME:10.9.0 --tag=gcr.io/$PROJECT_ID/node-builder.$BRANCH_NAME:10.x --build-arg=NPM_VERSION=6.4.0 --build-arg=YARN_VERSION=1.9.4 --build-arg=GITHUB_PAT=$$GITHUB_PAT .']
    secretEnv: ['GITHUB_PAT']
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker build --build-arg=NODE_VERSION=10.9.0 --build-arg=BRANCH_NAME=$BRANCH_NAME --tag=test:10.9.0 --build-arg=GITHUB_PAT=$$GITHUB_PAT test/']
    secretEnv: ['GITHUB_PAT']
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker run test:10.9.0']

  # node 8.11.4
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker build --target base --build-arg=NODE_VERSION=8.11.4 --tag=gcr.io/$PROJECT_ID/node-base.$BRANCH_NAME:8.11.4 --tag=gcr.io/$PROJECT_ID/node-base.$BRANCH_NAME:8.x --build-arg=NPM_VERSION=6.4.0 --build-arg=YARN_VERSION=1.9.4 --build-arg=GITHUB_PAT=$$GITHUB_PAT .']
    secretEnv: ['GITHUB_PAT']
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker build --build-arg=NODE_VERSION=8.11.4 --tag=gcr.io/$PROJECT_ID/node-fat-base.$BRANCH_NAME:8.11.4 --tag=gcr.io/$PROJECT_ID/node-fat-base.$BRANCH_NAME:8.x --build-arg=GITHUB_PAT=$$GITHUB_PAT fat-base.Dockerfile']
    secretEnv: ['GITHUB_PAT']
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker build --target builder --build-arg=NODE_VERSION=8.11.4 --tag=gcr.io/$PROJECT_ID/node-builder.$BRANCH_NAME:8.11.4 --tag=gcr.io/$PROJECT_ID/node-builder.$BRANCH_NAME:8.x --build-arg=NPM_VERSION=6.4.0 --build-arg=YARN_VERSION=1.9.4 --build-arg=GITHUB_PAT=$$GITHUB_PAT .']
    secretEnv: ['GITHUB_PAT']
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker build --build-arg=NODE_VERSION=8.11.4 --build-arg=BRANCH_NAME=$BRANCH_NAME --tag=test:8.11.4 --build-arg=GITHUB_PAT=$$GITHUB_PAT test/']
    secretEnv: ['GITHUB_PAT']
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker run test:8.11.4']
images: 
  - 'gcr.io/$PROJECT_ID/node-base.$BRANCH_NAME:10.9.0'
  - 'gcr.io/$PROJECT_ID/node-builder.$BRANCH_NAME:10.9.0'
  - 'gcr.io/$PROJECT_ID/node-base.$BRANCH_NAME:10.x'
  - 'gcr.io/$PROJECT_ID/node-builder.$BRANCH_NAME:10.x'
  - 'gcr.io/$PROJECT_ID/node-base.$BRANCH_NAME:8.11.4'
  - 'gcr.io/$PROJECT_ID/node-builder.$BRANCH_NAME:8.11.4'
  - 'gcr.io/$PROJECT_ID/node-base.$BRANCH_NAME:8.x'
  - 'gcr.io/$PROJECT_ID/node-builder.$BRANCH_NAME:8.x'
secrets:
- kmsKeyName: projects/connectedcars-staging/locations/global/keyRings/cloudbuilder/cryptoKeys/connectedcars-builder
  secretEnv:
    GITHUB_PAT: CiQAg7wCPfO2Tf9mtZoFWjAtX7whQ481af3gyGdM9WNK26B74UkSUQBefMgeHNh0KTsGybKReXDsFcbmed7f5sw97zSe9cswpKogENM5Ye0jiIu6NfebUpCnmJ9HVHmD/yBknlW4nn1VXBs7HYGiBSFZ52i2HyEopw==
timeout: 1200s
