steps:
  # Setup docker with buildkit and other fixes
  - name: "europe-west1-docker.pkg.dev/connectedcars-build/cloud-build-init/master"
  # Build all images
  - name: "gcr.io/cloud-builders/docker"
    entrypoint: "bash"
    args: ["-c", "./build-all.sh"]
    env:
      [
        "COMMIT_SHA=${COMMIT_SHA}",
        "BRANCH_NAME=${BRANCH_NAME}",
        "PROJECT_ID=${PROJECT_ID}",
        "PUSH=y",
      ]
    secretEnv: ["NPM_TOKEN"]
    timeout: 14400s
secrets:
  - kmsKeyName: projects/connectedcars-staging/locations/global/keyRings/cloudbuilder/cryptoKeys/connectedcars-builder
    secretEnv:
      NPM_TOKEN: CiQAg7wCPQZ8nNz6Rmw/rMQnSJwp6egVUm+W8hubsv4ptMnPzx8SUQBefMgebGw+Lw88YICroEwuQ/v4bPpvG/argq0lEoU1033FdwNZ0Kb+jrZBRqOizn7D9JYWb4YTSCcBJV795GAEAOvz54CIX05q/e0DjoNS5A==
timeout: 14460s
options:
  machineType: "E2_HIGHCPU_32"
