substitutions:
  _NODE_VERSION_11: 11.14.0
  _NODE_VERSION_10: 10.15.3
  _YARN_VERSION: 1.15.2
  _NPM_VERSION: 6.9.0
steps:
  # node 11.x
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker build --target base --build-arg=NODE_VERSION=${_NODE_VERSION_11} --build-arg=NPM_VERSION=${_NPM_VERSION} --build-arg=YARN_VERSION=${_YARN_VERSION} --tag=gcr.io/${PROJECT_ID}/node-base.${BRANCH_NAME}:${_NODE_VERSION_11} --tag=gcr.io/${PROJECT_ID}/node-base.${BRANCH_NAME}:11.x --build-arg=GITHUB_PAT=$$GITHUB_PAT .']
    secretEnv: ['GITHUB_PAT']
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker build --target builder --build-arg=NODE_VERSION=${_NODE_VERSION_11} --build-arg=NPM_VERSION=${_NPM_VERSION} --build-arg=YARN_VERSION=${_YARN_VERSION} --tag=gcr.io/${PROJECT_ID}/node-builder.${BRANCH_NAME}:${_NODE_VERSION_11} --tag=gcr.io/${PROJECT_ID}/node-builder.${BRANCH_NAME}:11.x --build-arg=GITHUB_PAT=$$GITHUB_PAT .']
    secretEnv: ['GITHUB_PAT']
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker build --build-arg=NODE_VERSION=${_NODE_VERSION_11} --build-arg=BRANCH_NAME=${BRANCH_NAME} --tag=test:${_NODE_VERSION_11} --build-arg=GITHUB_PAT=$$GITHUB_PAT test/']
    secretEnv: ['GITHUB_PAT']
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker run test:${_NODE_VERSION_11}']
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker build --build-arg=NODE_VERSION=${_NODE_VERSION_11} --build-arg=BRANCH_NAME=${BRANCH_NAME} --tag=gcr.io/${PROJECT_ID}/node-fat-base.${BRANCH_NAME}:${_NODE_VERSION_11} --tag=gcr.io/${PROJECT_ID}/node-fat-base.${BRANCH_NAME}:11.x --build-arg=GITHUB_PAT=$$GITHUB_PAT fat-base/']
    secretEnv: ['GITHUB_PAT']
  
  # node 10.x
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker build --target base --build-arg=NODE_VERSION=${_NODE_VERSION_10} --build-arg=NPM_VERSION=${_NPM_VERSION} --build-arg=YARN_VERSION=${_YARN_VERSION} --tag=gcr.io/${PROJECT_ID}/node-base.${BRANCH_NAME}:${_NODE_VERSION_10} --tag=gcr.io/${PROJECT_ID}/node-base.${BRANCH_NAME}:10.x --build-arg=GITHUB_PAT=$$GITHUB_PAT .']
    secretEnv: ['GITHUB_PAT']
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker build --target builder --build-arg=NODE_VERSION=${_NODE_VERSION_10} --build-arg=NPM_VERSION=${_NPM_VERSION} --build-arg=YARN_VERSION=${_YARN_VERSION} --tag=gcr.io/${PROJECT_ID}/node-builder.${BRANCH_NAME}:${_NODE_VERSION_10} --tag=gcr.io/${PROJECT_ID}/node-builder.${BRANCH_NAME}:10.x --build-arg=GITHUB_PAT=$$GITHUB_PAT .']
    secretEnv: ['GITHUB_PAT']
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker build --build-arg=NODE_VERSION=${_NODE_VERSION_10} --build-arg=BRANCH_NAME=${BRANCH_NAME} --tag=test:${_NODE_VERSION_10} --build-arg=GITHUB_PAT=$$GITHUB_PAT test/']
    secretEnv: ['GITHUB_PAT']
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker run test:${_NODE_VERSION_10}']
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', 'docker build --build-arg=NODE_VERSION=${_NODE_VERSION_10} --build-arg=BRANCH_NAME=${BRANCH_NAME} --tag=gcr.io/${PROJECT_ID}/node-fat-base.${BRANCH_NAME}:${_NODE_VERSION_10} --tag=gcr.io/${PROJECT_ID}/node-fat-base.${BRANCH_NAME}:10.x --build-arg=GITHUB_PAT=$$GITHUB_PAT fat-base/']
    secretEnv: ['GITHUB_PAT']
images: 
  - 'gcr.io/${PROJECT_ID}/node-base.${BRANCH_NAME}:11.x'
  - 'gcr.io/${PROJECT_ID}/node-base.${BRANCH_NAME}:${_NODE_VERSION_11}'
  - 'gcr.io/${PROJECT_ID}/node-fat-base.${BRANCH_NAME}:11.x'
  - 'gcr.io/${PROJECT_ID}/node-fat-base.${BRANCH_NAME}:${_NODE_VERSION_11}'
  - 'gcr.io/${PROJECT_ID}/node-builder.${BRANCH_NAME}:11.x'
  - 'gcr.io/${PROJECT_ID}/node-builder.${BRANCH_NAME}:${_NODE_VERSION_11}'
  - 'gcr.io/${PROJECT_ID}/node-base.${BRANCH_NAME}:10.x'
  - 'gcr.io/${PROJECT_ID}/node-base.${BRANCH_NAME}:${_NODE_VERSION_10}'
  - 'gcr.io/${PROJECT_ID}/node-fat-base.${BRANCH_NAME}:10.x'
  - 'gcr.io/${PROJECT_ID}/node-fat-base.${BRANCH_NAME}:${_NODE_VERSION_10}'
  - 'gcr.io/${PROJECT_ID}/node-builder.${BRANCH_NAME}:10.x'
  - 'gcr.io/${PROJECT_ID}/node-builder.${BRANCH_NAME}:${_NODE_VERSION_10}'
secrets:
- kmsKeyName: projects/connectedcars-staging/locations/global/keyRings/cloudbuilder/cryptoKeys/connectedcars-builder
  secretEnv:
    GITHUB_PAT: CiQAg7wCPfO2Tf9mtZoFWjAtX7whQ481af3gyGdM9WNK26B74UkSUQBefMgeHNh0KTsGybKReXDsFcbmed7f5sw97zSe9cswpKogENM5Ye0jiIu6NfebUpCnmJ9HVHmD/yBknlW4nn1VXBs7HYGiBSFZ52i2HyEopw==
timeout: 1200s
