steps:
  # Register qemu targets with linux
  - name: gcr.io/cloud-builders/docker
    args: ['run', '--rm', '--privileged', 'multiarch/qemu-user-static', '--reset', '-p', 'yes']
  # Create a new builder that supports multi arch and use this as instead
  - name: gcr.io/cloud-builders/docker
    args: ['buildx', 'create', '--name', 'multi-arch-builder', '--use']
  # List build targets
  - name: 'gcr.io/cloud-builders/docker'
    args: ['buildx', 'inspect', '--bootstrap']
  # copy build key to workspace
  - name: 'gcr.io/cloud-builders/gsutil'
    args: [
            'cp',
            'gs://connectedcars-staging-cloudbuilder-private/build.key',
            '.'
          ]
  # Build all images
  - name: 'gcr.io/cloud-builders/docker'
    entrypoint: 'bash'
    args: ['-c', './build-all.sh']
    secretEnv: ["NPM_TOKEN"]
    timeout: 2400s
secrets:
- kmsKeyName: projects/connectedcars-staging/locations/global/keyRings/cloudbuilder/cryptoKeys/connectedcars-builder
  secretEnv:
    GITHUB_PAT: CiQAg7wCPfO2Tf9mtZoFWjAtX7whQ481af3gyGdM9WNK26B74UkSUQBefMgeHNh0KTsGybKReXDsFcbmed7f5sw97zSe9cswpKogENM5Ye0jiIu6NfebUpCnmJ9HVHmD/yBknlW4nn1VXBs7HYGiBSFZ52i2HyEopw==
    NPM_TOKEN: CiQAg7wCPTQtGU4lDlteqQWahMhUcvH2pwDWOPaT3ZpFKei4yj4SUgBefMgeT52oO+OFIHJFMIPFJLTZ7fWStqGIWrvAxzKhVTIm7UgFR/WhVoG0nAQ/qCu3QbOCsRz+JGvBuvRKh90K4C1GIyBbDuBTuVN4rxCrkBg=
timeout: 4800s
